redis:
  addr: "redis:6379"

server:
  addr: ":8080"

rules:
  - name: default
    limit: 10
    window: 60s
    key_source: ip

  - name: auth
    match:
      path_prefix: /auth/login
    limit: 3
    window: 60s
    key_source: ip
